import { defineConfig } from 'tsup'

export default defineConfig({
  entry: {
    index: 'src/index.ts',
    'adapters/memory': 'src/persistence/memory.ts',
    'adapters/filesystem': 'src/persistence/filesystem.ts',
    'adapters/indexeddb': 'src/persistence/indexeddb.ts',
    'invalidation/noop': 'src/invalidation/noop.ts',
    'invalidation/filesystem': 'src/invalidation/filesystem.ts',
    'invalidation/broadcast-channel': 'src/invalidation/broadcast-channel.ts',
    'workers/entry': 'src/workers/worker-entry.ts',
    'vector/hnsw-build-worker': 'src/vector/hnsw-build-worker.ts',
    'languages/english': 'src/languages/english.ts',
    'languages/french': 'src/languages/french.ts',
    'languages/german': 'src/languages/german.ts',
    'languages/spanish': 'src/languages/spanish.ts',
    'languages/italian': 'src/languages/italian.ts',
    'languages/portuguese': 'src/languages/portuguese.ts',
    'languages/dutch': 'src/languages/dutch.ts',
    'languages/swedish': 'src/languages/swedish.ts',
    'languages/norwegian': 'src/languages/norwegian.ts',
    'languages/danish': 'src/languages/danish.ts',
    'languages/finnish': 'src/languages/finnish.ts',
    'languages/hungarian': 'src/languages/hungarian.ts',
    'languages/romanian': 'src/languages/romanian.ts',
    'languages/turkish': 'src/languages/turkish.ts',
    'languages/russian': 'src/languages/russian.ts',
    'languages/arabic': 'src/languages/arabic.ts',
    'languages/hindi': 'src/languages/hindi.ts',
    'languages/indonesian': 'src/languages/indonesian.ts',
    'languages/irish': 'src/languages/irish.ts',
    'languages/greek': 'src/languages/greek.ts',
    'languages/armenian': 'src/languages/armenian.ts',
    'languages/tamil': 'src/languages/tamil.ts',
    'languages/nepali': 'src/languages/nepali.ts',
    'languages/serbian': 'src/languages/serbian.ts',
    'languages/bulgarian': 'src/languages/bulgarian.ts',
    'languages/ukrainian': 'src/languages/ukrainian.ts',
    'languages/slovenian': 'src/languages/slovenian.ts',
    'languages/swahili': 'src/languages/swahili.ts',
    'languages/hausa': 'src/languages/hausa.ts',
    'languages/yoruba': 'src/languages/yoruba.ts',
    'languages/twi': 'src/languages/twi.ts',
    'languages/ga': 'src/languages/ga.ts',
    'languages/ewe': 'src/languages/ewe.ts',
    'languages/dagbani': 'src/languages/dagbani.ts',
    'languages/igbo': 'src/languages/igbo.ts',
    'languages/zulu': 'src/languages/zulu.ts',
    'languages/chinese': 'src/languages/chinese.ts',
    'languages/japanese': 'src/languages/japanese.ts',
    'languages/sanskrit': 'src/languages/sanskrit.ts',
  },
  format: ['esm'],
  dts: true,
  splitting: true,
  clean: true,
  treeshake: true,
  outExtension: () => ({ js: '.mjs' }),
  external: ['worker_threads', 'fs', 'path', 'os', 'crypto'],
})
