export const DEFAULT_PROMOTION_THRESHOLD = 1024
export const DEFAULT_FILTER_THRESHOLD = 0.03

export const ESTIMATED_MS_PER_TOMBSTONE = 0.05
export const ESTIMATED_MS_PER_VECTOR_REBUILD = 0.15

export const WORKER_BUILD_SIZE_THRESHOLD = 5000
export const WORKER_COPY_MIN_VECTORS = 1024

export const BUILD_CHUNK_SIZE = 100
export const REBUILD_REMOVED_RATIO = 0.2
