export const WASM_PAGE_BYTES = 65536
export const MAX_WASM_PAGES = 65536

export const VECTOR_STORE_INITIAL_CAPACITY = 16
export const VECTOR_BLOCK_INITIAL_SLOTS = 256

export const MAX_VECTOR_ORDINALS = 16_777_216
export const VECTOR_SCRATCH_SLOTS = 64
export const SCRATCH_SLOTS_PER_THREAD_POOL = 31
export const MAX_DOC_ID_TABLE_BYTES = 1_073_741_824

export const MAX_WORKER_COPIES = 64

export const VECTOR_SEARCH_TIMEOUT_MS = 30_000
export const VECTOR_SEARCH_LOAD_TIMEOUT_MS = 300_000
export const VECTOR_INSERT_TIMEOUT_MS = 600_000

export const QUANTIZATION_PADDING_FACTOR = 0.01

export const LOCK_SPIN_ITERATIONS = 128
export const LOCK_WAIT_SLICE_MS = 20

export const GRAPH_BUILD_DISPATCH_CHUNK = 64
export const GRAPH_BUILD_CHUNKS_IN_FLIGHT_PER_WORKER = 2
