export const TARGET_BLOCK_ENTRIES = 128
export const PRUNING_REJECTION_SLACK = 1e-12
export const MULTI_TERM_PRUNING_POSTINGS_THRESHOLD = 30_000
export const SCORE_BUFFER_INITIAL_TOUCHED_CAPACITY = 1024

export const SORT_COLUMN_MINIMUM_REBUILD_THRESHOLD = 1024
export const SORT_COLUMN_REBUILD_FRACTION_SHIFT = 2
