import type { IndexConfig, SchemaDefinition } from '../../../types/schema'

export const schema: SchemaDefinition = {
  title: 'string',
  description: 'string',
  price: 'number',
  inStock: 'boolean',
  category: 'enum',
}

export const indexConfig: IndexConfig = {
  schema,
  language: 'english',
}

export const products = [
  {
    title: 'Wireless Headphones',
    description: 'Bluetooth over-ear headphones with noise cancellation',
    price: 149,
    inStock: true,
    category: 'electronics',
  },
  {
    title: 'Running Shoes',
    description: 'Lightweight trail running shoes for off-road terrain',
    price: 89,
    inStock: true,
    category: 'sports',
  },
  {
    title: 'Cotton T-Shirt',
    description: 'Soft cotton crew neck t-shirt for everyday wear',
    price: 25,
    inStock: true,
    category: 'clothing',
  },
  {
    title: 'JavaScript Handbook',
    description: 'The definitive guide to learning JavaScript from scratch',
    price: 45,
    inStock: true,
    category: 'books',
  },
  {
    title: 'Ceramic Vase',
    description: 'Handcrafted ceramic vase for home decoration',
    price: 35,
    inStock: false,
    category: 'home',
  },
  {
    title: 'Wireless Mouse',
    description: 'Ergonomic wireless mouse with adjustable DPI settings',
    price: 39,
    inStock: true,
    category: 'electronics',
  },
  {
    title: 'Yoga Mat',
    description: 'Non-slip yoga mat with carrying strap included',
    price: 29,
    inStock: true,
    category: 'sports',
  },
  {
    title: 'Denim Jacket',
    description: 'Classic denim jacket with button closure and pockets',
    price: 79,
    inStock: true,
    category: 'clothing',
  },
  {
    title: 'Cooking Recipes',
    description: 'A collection of gourmet recipes for home cooks',
    price: 32,
    inStock: true,
    category: 'books',
  },
  {
    title: 'Table Lamp',
    description: 'Adjustable LED table lamp for reading and work desks',
    price: 55,
    inStock: true,
    category: 'home',
  },
  {
    title: 'Wireless Charger',
    description: 'Fast wireless charging pad compatible with all Qi devices',
    price: 29,
    inStock: true,
    category: 'electronics',
  },
  {
    title: 'Basketball',
    description: 'Official size outdoor basketball with textured grip',
    price: 35,
    inStock: false,
    category: 'sports',
  },
  {
    title: 'Winter Coat',
    description: 'Insulated winter coat with waterproof outer shell',
    price: 199,
    inStock: true,
    category: 'clothing',
  },
  {
    title: 'Science Fiction Anthology',
    description: 'Award-winning science fiction short stories',
    price: 18,
    inStock: true,
    category: 'books',
  },
  {
    title: 'Throw Pillow Set',
    description: 'Decorative throw pillows with removable covers',
    price: 42,
    inStock: true,
    category: 'home',
  },
  {
    title: 'Wireless Keyboard',
    description: 'Slim wireless keyboard with backlit keys',
    price: 69,
    inStock: true,
    category: 'electronics',
  },
  {
    title: 'Tennis Racket',
    description: 'Graphite tennis racket for intermediate players',
    price: 120,
    inStock: true,
    category: 'sports',
  },
  {
    title: 'Silk Scarf',
    description: 'Handmade silk scarf with floral print pattern',
    price: 55,
    inStock: true,
    category: 'clothing',
  },
  {
    title: 'History of Art',
    description: 'Visual history of art movements across centuries',
    price: 65,
    inStock: false,
    category: 'books',
  },
  {
    title: 'Scented Candle',
    description: 'Soy wax scented candle with vanilla and lavender',
    price: 22,
    inStock: true,
    category: 'home',
  },
  {
    title: 'Wireless Earbuds',
    description: 'True wireless earbuds with active noise cancellation',
    price: 129,
    inStock: true,
    category: 'electronics',
  },
  {
    title: 'Hiking Backpack',
    description: 'Durable hiking backpack with hydration bladder pocket',
    price: 95,
    inStock: true,
    category: 'sports',
  },
  {
    title: 'Linen Pants',
    description: 'Breathable linen pants for warm weather comfort',
    price: 65,
    inStock: true,
    category: 'clothing',
  },
  {
    title: 'Poetry Collection',
    description: 'Contemporary poetry from emerging voices worldwide',
    price: 16,
    inStock: true,
    category: 'books',
  },
  {
    title: 'Wall Clock',
    description: 'Minimalist wall clock with silent movement mechanism',
    price: 48,
    inStock: true,
    category: 'home',
  },
  {
    title: 'Portable Speaker',
    description: 'Waterproof portable Bluetooth speaker for outdoor use',
    price: 79,
    inStock: true,
    category: 'electronics',
  },
  {
    title: 'Swimming Goggles',
    description: 'Anti-fog swimming goggles with UV protection lenses',
    price: 24,
    inStock: true,
    category: 'sports',
  },
  {
    title: 'Wool Sweater',
    description: 'Merino wool pullover sweater for cold seasons',
    price: 110,
    inStock: false,
    category: 'clothing',
  },
  {
    title: 'Gardening Guide',
    description: 'Step-by-step gardening guide for beginners',
    price: 22,
    inStock: true,
    category: 'books',
  },
  {
    title: 'Doormat',
    description: 'Weather-resistant coir doormat for front entrance',
    price: 28,
    inStock: true,
    category: 'home',
  },
  {
    title: 'USB-C Hub',
    description: 'Multi-port USB-C hub with HDMI and ethernet',
    price: 59,
    inStock: true,
    category: 'electronics',
  },
  {
    title: 'Jump Rope',
    description: 'Adjustable speed jump rope for cardio training',
    price: 15,
    inStock: true,
    category: 'sports',
  },
  {
    title: 'Leather Belt',
    description: 'Genuine leather belt with brushed nickel buckle',
    price: 45,
    inStock: true,
    category: 'clothing',
  },
  {
    title: 'Travel Memoir',
    description: 'Captivating travel stories from Southeast Asia',
    price: 19,
    inStock: true,
    category: 'books',
  },
  {
    title: 'Picture Frame',
    description: 'Wooden picture frame for standard photo sizes',
    price: 18,
    inStock: true,
    category: 'home',
  },
  {
    title: 'Webcam HD',
    description: 'High-definition webcam with built-in microphone',
    price: 89,
    inStock: true,
    category: 'electronics',
  },
  {
    title: 'Resistance Bands',
    description: 'Set of five resistance bands for strength training',
    price: 20,
    inStock: true,
    category: 'sports',
  },
  {
    title: 'Rain Boots',
    description: 'Waterproof rubber rain boots with traction sole',
    price: 58,
    inStock: true,
    category: 'clothing',
  },
  {
    title: 'Thriller Novel',
    description: 'Page-turning thriller novel by bestselling author',
    price: 14,
    inStock: true,
    category: 'books',
  },
  {
    title: 'Bath Towel Set',
    description: 'Plush cotton bath towel set in assorted colors',
    price: 38,
    inStock: true,
    category: 'home',
  },
  {
    title: 'Wireless Router',
    description: 'Dual-band wireless router with parental controls',
    price: 109,
    inStock: true,
    category: 'electronics',
  },
  {
    title: 'Dumbbells Set',
    description: 'Adjustable dumbbells set for home gym workouts',
    price: 150,
    inStock: true,
    category: 'sports',
  },
  {
    title: 'Polo Shirt',
    description: 'Classic polo shirt in pique cotton fabric',
    price: 40,
    inStock: true,
    category: 'clothing',
  },
  {
    title: 'Biographies Bundle',
    description: 'Collection of biographies of world-changing leaders',
    price: 38,
    inStock: true,
    category: 'books',
  },
  {
    title: 'Coaster Set',
    description: 'Cork coaster set with artistic prints for tables',
    price: 15,
    inStock: true,
    category: 'home',
  },
  {
    title: 'Monitor Stand',
    description: 'Adjustable monitor stand with cable management',
    price: 45,
    inStock: true,
    category: 'electronics',
  },
  {
    title: 'Soccer Ball',
    description: 'Match-quality soccer ball for grass and turf play',
    price: 30,
    inStock: true,
    category: 'sports',
  },
  {
    title: 'Flannel Shirt',
    description: 'Soft flannel button-down shirt in plaid pattern',
    price: 35,
    inStock: true,
    category: 'clothing',
  },
  {
    title: 'Philosophy Intro',
    description: 'Introduction to philosophy for curious minds',
    price: 27,
    inStock: false,
    category: 'books',
  },
  {
    title: 'Bookshelf Organizer',
    description: 'Stackable bookshelf organizer with adjustable dividers',
    price: 33,
    inStock: true,
    category: 'home',
  },
]
