export const DEFAULT_CHECKPOINT_INTERVAL_MS = 300_000
export const DEFAULT_CHECKPOINT_MUTATION_THRESHOLD = 100_000
export const DEFAULT_ASYNC_FLUSH_INTERVAL_MS = 1_000

export const DEFAULT_SEGMENT_MAX_BYTES = 67_108_864
export const DEFAULT_TARGET_SEGMENT_BYTES = 8_388_608
export const DEFAULT_COMPACTION_THRESHOLD = 12

export const CHECKPOINT_WORKER_TIMEOUT_MS = 600_000
export const CHECKPOINT_TIMEOUT_RECOVERY_BACKOFF_MS = 50
