export const DEFAULT_CHECKPOINT_INTERVAL_MS = 300_000
export const DEFAULT_CHECKPOINT_MUTATION_THRESHOLD = 100_000
export const DEFAULT_ASYNC_FLUSH_INTERVAL_MS = 1_000
export const DIRECTORY_IDENTITY_CHECK_INTERVAL_MS = 1_000
export const DIRECTORY_LOCK_ATTEMPTS = 3
export const DIRECTORY_LOCK_SETTLE_MS = 50
export const DIRECTORY_LOCK_PROCESS_START_TOLERANCE_MS = 1_000

export const DEFAULT_SEGMENT_MAX_BYTES = 67_108_864
export const DEFAULT_TARGET_SEGMENT_BYTES = 8_388_608
export const DEFAULT_COMPACTION_THRESHOLD = 12
export const COMPACTION_LARGEST_MERGED_DOCUMENT_COUNT = 200_000
export const WHOLE_PARTITION_MIN_CHANGED_SHARE = 0.5
export const WHOLE_PARTITION_LARGEST_DOCUMENT_COUNT = 100_000
export const LOG_RECORDS_PER_CHECKPOINT = 100_000
export const WRITES_STALL_ABOVE_UNCHECKPOINTED_BYTES = 2_147_483_648

export const CHECKPOINT_WORKER_TIMEOUT_MS = 600_000
export const CHECKPOINT_WORKER_HEARTBEAT_MS = 5_000
export const CHECKPOINT_WORKER_IDLE_MS = 5_000
export const CHECKPOINT_TIMEOUT_RECOVERY_BACKOFF_MS = 50
