export const IDLE_HEAP_CLEANUP_CHECK_MS = 1_000
export const IDLE_HEAP_CLEANUP_QUIET_CHECKS = 2
export const IDLE_HEAP_CLEANUP_MAX_UTILISATION = 0.1
export const IDLE_HEAP_CLEANUP_MAX_GROWTH_BYTES = 4 * 1024 * 1024
export const IDLE_HEAP_CLEANUP_MIN_RECLAIMABLE_BYTES = 64 * 1024 * 1024
