export const MAX_NESTING_DEPTH = 4
export const MAX_DOCUMENT_NESTING_DEPTH = 32
export const DEFAULT_PATTERN_VALUE_LIMIT = 8_192
export const MIN_PATTERN_VALUE_LIMIT = 1
export const MAX_PATTERN_VALUE_LIMIT = 65_536
