import { MIN_DOCUMENTS_FOR_SEGMENTS } from '../constants'

export const DEFAULT_COPY_THRESHOLD = 1_000
export const DEFAULT_COPY_IDLE_TIMEOUT_MS = 300_000

export const COMPACTION_SEGMENT_TRIGGER = 8
export const IDLE_MERGE_DELAY_MS = 1_000

export const LIVE_TAIL_FREEZE_FLOOR = MIN_DOCUMENTS_FOR_SEGMENTS
export const LIVE_TAIL_FLUSH_DOCUMENTS = 5_000

export const MAX_PENDING_REPLICATION_DOCUMENTS = 20_000
export const REPLICATION_WINDOW = 32
export const LOAD_BUFFER_YIELD_INTERVAL = 1_000

export const MAIN_COPY_LONE_QUERY_DOCUMENTS = 50_000

export const POOL_RESTART_DELAY_MS = 1_000
export const POOL_RESTART_DELAY_MAX_MS = 60_000
