import type { ProductDoc } from './fixtures'

export const clothingItems: ProductDoc[] = [
  {
    title: 'Cotton T-Shirt',
    description: 'Soft cotton crew neck t-shirt for everyday casual wear',
    price: 25,
    inStock: true,
    category: 'clothing',
  },
  {
    title: 'Denim Jacket',
    description: 'Classic denim jacket with button closure and front pockets',
    price: 79,
    inStock: true,
    category: 'clothing',
  },
  {
    title: 'Winter Coat',
    description: 'Insulated winter coat with waterproof outer shell and hood',
    price: 199,
    inStock: true,
    category: 'clothing',
  },
  {
    title: 'Silk Scarf',
    description: 'Handmade silk scarf with floral print and fringed edges',
    price: 55,
    inStock: true,
    category: 'clothing',
  },
  {
    title: 'Linen Pants',
    description: 'Breathable linen pants for warm weather comfort and style',
    price: 65,
    inStock: true,
    category: 'clothing',
  },
  {
    title: 'Wool Sweater',
    description: 'Merino wool pullover sweater for cold season layering',
    price: 110,
    inStock: false,
    category: 'clothing',
  },
  {
    title: 'Leather Belt',
    description: 'Genuine leather belt with brushed nickel buckle and stitching',
    price: 45,
    inStock: true,
    category: 'clothing',
  },
  {
    title: 'Rain Boots',
    description: 'Waterproof rubber rain boots with traction sole for wet days',
    price: 58,
    inStock: true,
    category: 'clothing',
  },
  {
    title: 'Polo Shirt',
    description: 'Classic polo shirt in pique cotton fabric for smart casual looks',
    price: 40,
    inStock: true,
    category: 'clothing',
  },
  {
    title: 'Flannel Shirt',
    description: 'Soft flannel button-down shirt in plaid pattern for autumn',
    price: 35,
    inStock: true,
    category: 'clothing',
  },
  {
    title: 'Running Shorts',
    description: 'Lightweight running shorts with moisture-wicking fabric',
    price: 30,
    inStock: true,
    category: 'clothing',
  },
  {
    title: 'Cashmere Cardigan',
    description: 'Luxurious cashmere cardigan with mother-of-pearl buttons',
    price: 189,
    inStock: true,
    category: 'clothing',
  },
  {
    title: 'Cargo Pants',
    description: 'Durable cargo pants with multiple pockets for utility',
    price: 55,
    inStock: true,
    category: 'clothing',
  },
  {
    title: 'Sundress',
    description: 'Flowing sundress with adjustable straps and floral print',
    price: 48,
    inStock: true,
    category: 'clothing',
  },
  {
    title: 'Athletic Socks Pack',
    description: 'Six-pack of cushioned athletic socks for daily training',
    price: 18,
    inStock: true,
    category: 'clothing',
  },
]

export const sportsItems: ProductDoc[] = [
  {
    title: 'Running Shoes',
    description: 'Lightweight trail running shoes for off-road terrain and endurance',
    price: 89,
    inStock: true,
    category: 'sports',
  },
  {
    title: 'Yoga Mat',
    description: 'Non-slip yoga mat with carrying strap for studio and home',
    price: 29,
    inStock: true,
    category: 'sports',
  },
  {
    title: 'Basketball',
    description: 'Official size outdoor basketball with textured grip surface',
    price: 35,
    inStock: false,
    category: 'sports',
  },
  {
    title: 'Tennis Racket',
    description: 'Graphite tennis racket for intermediate and advanced players',
    price: 120,
    inStock: true,
    category: 'sports',
  },
  {
    title: 'Hiking Backpack',
    description: 'Durable hiking backpack with hydration bladder pocket included',
    price: 95,
    inStock: true,
    category: 'sports',
  },
  {
    title: 'Swimming Goggles',
    description: 'Anti-fog swimming goggles with UV protection and comfort fit',
    price: 24,
    inStock: true,
    category: 'sports',
  },
  {
    title: 'Jump Rope',
    description: 'Adjustable speed jump rope for cardio training at any level',
    price: 15,
    inStock: true,
    category: 'sports',
  },
  {
    title: 'Dumbbells Set',
    description: 'Adjustable dumbbells set for home gym strength workouts',
    price: 150,
    inStock: true,
    category: 'sports',
  },
  {
    title: 'Soccer Ball',
    description: 'Match-quality soccer ball for grass and turf playing surfaces',
    price: 30,
    inStock: true,
    category: 'sports',
  },
  {
    title: 'Resistance Bands',
    description: 'Set of five resistance bands for strength and flexibility training',
    price: 20,
    inStock: true,
    category: 'sports',
  },
  {
    title: 'Cycling Helmet',
    description: 'Aerodynamic cycling helmet with ventilation and visor',
    price: 65,
    inStock: true,
    category: 'sports',
  },
  {
    title: 'Boxing Gloves',
    description: 'Professional boxing gloves with wrist support padding',
    price: 55,
    inStock: true,
    category: 'sports',
  },
  {
    title: 'Foam Roller',
    description: 'High-density foam roller for muscle recovery and stretching',
    price: 25,
    inStock: true,
    category: 'sports',
  },
  {
    title: 'Badminton Set',
    description: 'Complete badminton set with rackets, shuttlecocks, and net',
    price: 42,
    inStock: true,
    category: 'sports',
  },
  {
    title: 'Fishing Rod',
    description: 'Telescopic fishing rod with spinning reel for freshwater',
    price: 75,
    inStock: false,
    category: 'sports',
  },
]

export const homeItems: ProductDoc[] = [
  {
    title: 'Ceramic Vase',
    description: 'Handcrafted ceramic vase for home decoration and flower displays',
    price: 35,
    inStock: false,
    category: 'home',
  },
  {
    title: 'Table Lamp',
    description: 'Adjustable LED table lamp for reading and productive work sessions',
    price: 55,
    inStock: true,
    category: 'home',
  },
  {
    title: 'Throw Pillow Set',
    description: 'Decorative throw pillows with removable washable covers',
    price: 42,
    inStock: true,
    category: 'home',
  },
  {
    title: 'Scented Candle',
    description: 'Soy wax scented candle with vanilla and lavender fragrance',
    price: 22,
    inStock: true,
    category: 'home',
  },
  {
    title: 'Wall Clock',
    description: 'Minimalist wall clock with silent movement for quiet rooms',
    price: 48,
    inStock: true,
    category: 'home',
  },
  {
    title: 'Doormat',
    description: 'Weather-resistant coir doormat for front entrance welcome',
    price: 28,
    inStock: true,
    category: 'home',
  },
  {
    title: 'Picture Frame',
    description: 'Wooden picture frame for standard photo sizes and art prints',
    price: 18,
    inStock: true,
    category: 'home',
  },
  {
    title: 'Bath Towel Set',
    description: 'Plush cotton bath towel set in assorted colors for bathroom',
    price: 38,
    inStock: true,
    category: 'home',
  },
  {
    title: 'Coaster Set',
    description: 'Cork coaster set with artistic prints for coffee tables',
    price: 15,
    inStock: true,
    category: 'home',
  },
  {
    title: 'Bookshelf Organizer',
    description: 'Stackable bookshelf organizer with adjustable dividers',
    price: 33,
    inStock: true,
    category: 'home',
  },
  {
    title: 'Kitchen Timer',
    description: 'Digital kitchen timer with magnetic back and loud alarm',
    price: 12,
    inStock: true,
    category: 'home',
  },
  {
    title: 'Storage Baskets',
    description: 'Woven storage baskets for closet and shelf organization',
    price: 26,
    inStock: true,
    category: 'home',
  },
  {
    title: 'Plant Pot Set',
    description: 'Set of three ceramic plant pots with drainage holes',
    price: 30,
    inStock: true,
    category: 'home',
  },
  {
    title: 'Shower Curtain',
    description: 'Waterproof polyester shower curtain with minimalist design',
    price: 20,
    inStock: true,
    category: 'home',
  },
  {
    title: 'Cutting Board',
    description: 'Bamboo cutting board with juice groove and handle',
    price: 24,
    inStock: true,
    category: 'home',
  },
]
