import type { ProductDoc } from './fixtures'

export const electronicsItems: ProductDoc[] = [
  {
    title: 'Wireless Headphones',
    description: 'Bluetooth over-ear headphones with noise cancellation and long battery life',
    price: 149,
    inStock: true,
    category: 'electronics',
  },
  {
    title: 'Wireless Mouse',
    description: 'Ergonomic wireless mouse with adjustable DPI settings and silent clicks',
    price: 39,
    inStock: true,
    category: 'electronics',
  },
  {
    title: 'Wireless Keyboard',
    description: 'Slim wireless keyboard with backlit keys for comfortable typing',
    price: 69,
    inStock: true,
    category: 'electronics',
  },
  {
    title: 'Wireless Charger',
    description: 'Fast wireless charging pad compatible with all Qi enabled devices',
    price: 29,
    inStock: true,
    category: 'electronics',
  },
  {
    title: 'Wireless Earbuds',
    description: 'True wireless earbuds with active noise cancellation technology',
    price: 129,
    inStock: true,
    category: 'electronics',
  },
  {
    title: 'Portable Speaker',
    description: 'Waterproof portable Bluetooth speaker for outdoor adventures',
    price: 79,
    inStock: true,
    category: 'electronics',
  },
  {
    title: 'USB-C Hub',
    description: 'Multi-port USB-C hub with HDMI output and ethernet connectivity',
    price: 59,
    inStock: false,
    category: 'electronics',
  },
  {
    title: 'Webcam HD',
    description: 'High-definition webcam with built-in microphone for video calls',
    price: 89,
    inStock: true,
    category: 'electronics',
  },
  {
    title: 'Wireless Router',
    description: 'Dual-band wireless router with parental controls and guest network',
    price: 109,
    inStock: true,
    category: 'electronics',
  },
  {
    title: 'Monitor Stand',
    description: 'Adjustable monitor stand with cable management and storage drawer',
    price: 45,
    inStock: true,
    category: 'electronics',
  },
  {
    title: 'Mechanical Keyboard',
    description: 'Cherry MX mechanical keyboard with RGB lighting effects',
    price: 159,
    inStock: true,
    category: 'electronics',
  },
  {
    title: 'Gaming Mouse',
    description: 'High-precision gaming mouse with programmable macro buttons',
    price: 75,
    inStock: true,
    category: 'electronics',
  },
  {
    title: 'Noise Cancelling Headset',
    description: 'Over-ear noise cancelling headset for professional meetings',
    price: 199,
    inStock: true,
    category: 'electronics',
  },
  {
    title: 'Laptop Cooling Pad',
    description: 'Slim laptop cooling pad with dual fans and adjustable height',
    price: 35,
    inStock: true,
    category: 'electronics',
  },
  {
    title: 'External SSD',
    description: 'Portable external SSD with 1TB storage and fast transfer speeds',
    price: 119,
    inStock: false,
    category: 'electronics',
  },
]

export const booksItems: ProductDoc[] = [
  {
    title: 'JavaScript Handbook',
    description: 'The definitive guide to learning JavaScript from fundamentals to advanced',
    price: 45,
    inStock: true,
    category: 'books',
  },
  {
    title: 'Cooking Recipes',
    description: 'A collection of gourmet recipes for home cooks and food enthusiasts',
    price: 32,
    inStock: true,
    category: 'books',
  },
  {
    title: 'Science Fiction Anthology',
    description: 'Award-winning science fiction short stories from visionary authors',
    price: 18,
    inStock: true,
    category: 'books',
  },
  {
    title: 'History of Art',
    description: 'Visual history of art movements across centuries and civilizations',
    price: 65,
    inStock: false,
    category: 'books',
  },
  {
    title: 'Poetry Collection',
    description: 'Contemporary poetry from emerging voices around the globe',
    price: 16,
    inStock: true,
    category: 'books',
  },
  {
    title: 'Gardening Guide',
    description: 'Step-by-step gardening guide for beginners who want green thumbs',
    price: 22,
    inStock: true,
    category: 'books',
  },
  {
    title: 'Travel Memoir',
    description: 'Captivating travel stories from Southeast Asia and the Pacific',
    price: 19,
    inStock: true,
    category: 'books',
  },
  {
    title: 'Thriller Novel',
    description: 'Page-turning thriller novel by a bestselling mystery author',
    price: 14,
    inStock: true,
    category: 'books',
  },
  {
    title: 'Biographies Bundle',
    description: 'Collection of biographies of world-changing leaders and innovators',
    price: 38,
    inStock: true,
    category: 'books',
  },
  {
    title: 'Philosophy Intro',
    description: 'Introduction to philosophy for curious minds and critical thinkers',
    price: 27,
    inStock: false,
    category: 'books',
  },
  {
    title: 'Machine Learning Primer',
    description: 'Hands-on introduction to machine learning algorithms and applications',
    price: 52,
    inStock: true,
    category: 'books',
  },
  {
    title: 'Creative Writing Workshop',
    description: 'Practical exercises for developing your creative writing skills',
    price: 24,
    inStock: true,
    category: 'books',
  },
  {
    title: 'World History Atlas',
    description: 'Illustrated atlas covering world history from ancient to present',
    price: 48,
    inStock: true,
    category: 'books',
  },
  {
    title: 'Psychology Basics',
    description: 'Foundations of psychology for students and lifelong learners',
    price: 33,
    inStock: true,
    category: 'books',
  },
  {
    title: 'Economics Explained',
    description: 'Clear explanations of economic principles and market behavior',
    price: 29,
    inStock: true,
    category: 'books',
  },
]
