export const MAX_LAYER_CAP = 32
export const MAX_M = 512
export const INITIAL_UPPER_SLOTS = 64
export const INITIAL_LIST_CAPACITY = 64

export const COMPACTION_TOMBSTONE_RATIO = 0.1
export const COMPACTION_ABSOLUTE_THRESHOLD = 1000
export const SQ8_OVERSELECTION_FACTOR = 2
export const SQ8_RERANK_FLOOR = 10
