import type { Product } from './fixtures'

export const electronicsProducts: Product[] = [
  {
    title: 'Wireless Bluetooth Headphones',
    description: 'Premium over-ear headphones with active noise cancellation and 30-hour battery life.',
    price: 149.99,
    inStock: true,
    category: 'electronics',
  },
  {
    title: 'USB-C Fast Charging Cable',
    description: 'Durable braided cable for fast charging and data transfer at high speeds.',
    price: 12.99,
    inStock: true,
    category: 'electronics',
  },
  {
    title: 'Mechanical Gaming Keyboard',
    description: 'RGB backlit keyboard with cherry switches for responsive typing and gaming.',
    price: 89.99,
    inStock: true,
    category: 'electronics',
  },
  {
    title: 'Portable Bluetooth Speaker',
    description: 'Waterproof speaker with 360-degree sound and built-in microphone.',
    price: 59.99,
    inStock: true,
    category: 'electronics',
  },
  {
    title: '4K Ultra HD Monitor',
    description: 'IPS display with wide color gamut and adjustable stand for professional work.',
    price: 429.99,
    inStock: false,
    category: 'electronics',
  },
  {
    title: 'Wireless Optical Mouse',
    description: 'Ergonomic mouse with adjustable DPI settings and long battery life.',
    price: 29.99,
    inStock: true,
    category: 'electronics',
  },
  {
    title: 'Noise Cancelling Earbuds',
    description: 'True wireless earbuds with active noise cancellation and transparency mode.',
    price: 199.99,
    inStock: true,
    category: 'electronics',
  },
  {
    title: 'HDMI to USB-C Adapter',
    description: 'Compact adapter for connecting displays to modern laptops and tablets.',
    price: 19.99,
    inStock: true,
    category: 'electronics',
  },
  {
    title: 'Smart Home Hub Controller',
    description: 'Central hub for managing all connected smart devices throughout your house.',
    price: 79.99,
    inStock: false,
    category: 'electronics',
  },
  {
    title: 'Laptop Cooling Pad',
    description: 'Slim cooling pad with dual fans and adjustable angle for better airflow.',
    price: 34.99,
    inStock: true,
    category: 'electronics',
  },
  {
    title: 'Portable Power Bank',
    description: 'High capacity power bank with dual USB ports for charging on the go.',
    price: 39.99,
    inStock: true,
    category: 'electronics',
  },
  {
    title: 'Digital Drawing Tablet',
    description: 'Pressure-sensitive tablet for digital art and graphic design workflows.',
    price: 249.99,
    inStock: true,
    category: 'electronics',
  },
  {
    title: 'Webcam HD 1080p',
    description: 'Wide-angle webcam with built-in microphone for video calls and streaming.',
    price: 49.99,
    inStock: true,
    category: 'electronics',
  },
  {
    title: 'External SSD Drive 1TB',
    description: 'Compact solid state drive with fast read and write speeds for backup.',
    price: 109.99,
    inStock: true,
    category: 'electronics',
  },
  {
    title: 'Wireless Charging Pad',
    description: 'Qi-compatible charging pad for phones and earbuds with LED indicator.',
    price: 24.99,
    inStock: true,
    category: 'electronics',
  },
  {
    title: 'Smart LED Desk Lamp',
    description: 'Adjustable desk lamp with color temperature control and dimming options.',
    price: 44.99,
    inStock: true,
    category: 'electronics',
  },
  {
    title: 'Bluetooth Audio Receiver',
    description: 'Small receiver that adds wireless audio capability to any wired speaker system.',
    price: 22.99,
    inStock: false,
    category: 'electronics',
  },
  {
    title: 'USB Microphone Studio Grade',
    description: 'Condenser microphone with cardioid pattern for podcasting and recording.',
    price: 129.99,
    inStock: true,
    category: 'electronics',
  },
  {
    title: 'Network Ethernet Switch',
    description: 'Eight-port gigabit switch for reliable wired networking at home or office.',
    price: 29.99,
    inStock: true,
    category: 'electronics',
  },
  {
    title: 'Cable Management Kit',
    description: 'Complete set of clips, ties, and sleeves for organizing desk cables neatly.',
    price: 14.99,
    inStock: true,
    category: 'electronics',
  },
]
