import type { Product } from './fixtures'

export const homeProducts: Product[] = [
  {
    title: 'Stainless Steel Water Filter',
    description: 'Countertop water filter removing contaminants while preserving minerals.',
    price: 89.99,
    inStock: true,
    category: 'home',
  },
  {
    title: 'Bamboo Cutting Board Set',
    description: 'Three-piece cutting board set with juice grooves and easy-grip handles.',
    price: 29.99,
    inStock: true,
    category: 'home',
  },
  {
    title: 'Cast Iron Skillet 12-Inch',
    description: 'Pre-seasoned cast iron pan for searing, baking, and stovetop cooking.',
    price: 34.99,
    inStock: true,
    category: 'home',
  },
  {
    title: 'Ceramic Plant Pot Collection',
    description: 'Set of four decorative ceramic pots in varying sizes for indoor plants.',
    price: 44.99,
    inStock: true,
    category: 'home',
  },
  {
    title: 'Memory Foam Pillow',
    description: 'Contoured memory foam pillow for proper neck alignment during sleep.',
    price: 49.99,
    inStock: true,
    category: 'home',
  },
  {
    title: 'Automatic Soap Dispenser',
    description: 'Touchless infrared sensor dispenser with adjustable foam volume control.',
    price: 24.99,
    inStock: true,
    category: 'home',
  },
  {
    title: 'LED String Lights Warm',
    description: 'Fairy string lights with warm white LEDs for ambient room decoration.',
    price: 14.99,
    inStock: true,
    category: 'home',
  },
  {
    title: 'Microfiber Cleaning Cloths',
    description: 'Pack of twelve reusable microfiber cloths for streak-free cleaning.',
    price: 12.99,
    inStock: true,
    category: 'home',
  },
  {
    title: 'French Press Coffee Maker',
    description: 'Borosilicate glass press with stainless steel frame for rich coffee.',
    price: 29.99,
    inStock: true,
    category: 'home',
  },
  {
    title: 'Organic Cotton Bed Sheets',
    description: 'Percale weave bed sheet set in organic cotton for a cool sleep surface.',
    price: 79.99,
    inStock: false,
    category: 'home',
  },
  {
    title: 'Drawer Organizer Expandable',
    description: 'Adjustable bamboo organizer for utensils, tools, and desk accessories.',
    price: 22.99,
    inStock: true,
    category: 'home',
  },
  {
    title: 'Essential Oil Diffuser',
    description: 'Ultrasonic aroma diffuser with color-changing LED and timer settings.',
    price: 34.99,
    inStock: true,
    category: 'home',
  },
  {
    title: 'Stainless Steel Mixing Bowls',
    description: 'Nesting bowl set with non-slip base and measurement markings inside.',
    price: 27.99,
    inStock: true,
    category: 'home',
  },
  {
    title: 'Wall Mounted Shelf Set',
    description: 'Floating shelves in natural wood finish for books and decorative items.',
    price: 39.99,
    inStock: true,
    category: 'home',
  },
  {
    title: 'Silicone Baking Mat Set',
    description: 'Two non-stick baking mats fitting standard sheet pans for even baking.',
    price: 16.99,
    inStock: true,
    category: 'home',
  },
  {
    title: 'Insulated Travel Mug',
    description: 'Double-wall vacuum mug keeping drinks hot for eight hours on the go.',
    price: 24.99,
    inStock: true,
    category: 'home',
  },
  {
    title: 'Bathroom Shower Caddy',
    description: 'Rust-proof stainless steel caddy with hooks for organized shower storage.',
    price: 19.99,
    inStock: true,
    category: 'home',
  },
  {
    title: 'Electric Kettle Temperature',
    description: 'Variable temperature kettle with keep-warm function for tea and pour-over.',
    price: 54.99,
    inStock: true,
    category: 'home',
  },
  {
    title: 'Kitchen Scale Digital',
    description: 'Precision digital scale with tare function and backlit display for cooking.',
    price: 18.99,
    inStock: true,
    category: 'home',
  },
  {
    title: 'Vacuum Storage Bags Large',
    description: 'Space-saving vacuum bags for compressing blankets, pillows, and clothing.',
    price: 21.99,
    inStock: false,
    category: 'home',
  },
]
