import type { Product } from './fixtures'

export const booksProducts: Product[] = [
  {
    title: 'Modern JavaScript Programming',
    description: 'A thorough guide to JavaScript covering ES6 features and async patterns.',
    price: 39.99,
    inStock: true,
    category: 'books',
  },
  {
    title: 'Data Structures and Algorithms',
    description: 'Learn fundamental computer science concepts with practical coding examples.',
    price: 49.99,
    inStock: true,
    category: 'books',
  },
  {
    title: 'The Art of Clean Code',
    description: 'Principles and patterns for writing maintainable and readable software.',
    price: 34.99,
    inStock: true,
    category: 'books',
  },
  {
    title: 'Introduction to Machine Learning',
    description: 'Beginner-friendly guide to ML concepts with Python implementations.',
    price: 54.99,
    inStock: false,
    category: 'books',
  },
  {
    title: 'Distributed Systems Design',
    description: 'Architecture patterns for building scalable and fault-tolerant systems.',
    price: 59.99,
    inStock: true,
    category: 'books',
  },
  {
    title: 'TypeScript in Practice',
    description: 'Hands-on examples for building type-safe applications with TypeScript.',
    price: 44.99,
    inStock: true,
    category: 'books',
  },
  {
    title: 'Database Internals Explained',
    description: 'Deep exploration of storage engines, indexing, and query optimization.',
    price: 64.99,
    inStock: true,
    category: 'books',
  },
  {
    title: 'Web Security Fundamentals',
    description: 'Essential knowledge for protecting web applications from common threats.',
    price: 29.99,
    inStock: true,
    category: 'books',
  },
  {
    title: 'Cloud Native Architecture',
    description: 'Building applications designed for containerized cloud environments.',
    price: 49.99,
    inStock: false,
    category: 'books',
  },
  {
    title: 'Functional Programming Guide',
    description: 'Explore functional paradigms and how they improve code quality.',
    price: 42.99,
    inStock: true,
    category: 'books',
  },
  {
    title: 'DevOps Handbook Revised',
    description: 'Strategies for continuous delivery and operational excellence in teams.',
    price: 37.99,
    inStock: true,
    category: 'books',
  },
  {
    title: 'Network Programming with Go',
    description: 'Build networked services and distributed applications using Go.',
    price: 47.99,
    inStock: true,
    category: 'books',
  },
  {
    title: 'Linux Command Line Mastery',
    description: 'From basic commands to shell scripting for system administration.',
    price: 32.99,
    inStock: true,
    category: 'books',
  },
  {
    title: 'API Design Patterns',
    description: 'Proven patterns for designing consistent and user-friendly REST APIs.',
    price: 52.99,
    inStock: true,
    category: 'books',
  },
  {
    title: 'Concurrency in Rust',
    description: 'Safe concurrent programming techniques using the Rust ownership model.',
    price: 46.99,
    inStock: false,
    category: 'books',
  },
  {
    title: 'Site Reliability Engineering',
    description: 'Principles for running reliable production systems at scale.',
    price: 55.99,
    inStock: true,
    category: 'books',
  },
  {
    title: 'Microservices Architecture',
    description: 'Designing loosely coupled services for large-scale applications.',
    price: 48.99,
    inStock: true,
    category: 'books',
  },
  {
    title: 'Graph Databases in Action',
    description: 'Modeling and querying connected data using graph database technologies.',
    price: 41.99,
    inStock: true,
    category: 'books',
  },
  {
    title: 'Test-Driven Development Guide',
    description: 'Write better software by letting tests drive your design decisions.',
    price: 36.99,
    inStock: true,
    category: 'books',
  },
  {
    title: 'Operating Systems Concepts',
    description: 'Core OS topics including processes, memory management, and file systems.',
    price: 69.99,
    inStock: true,
    category: 'books',
  },
]
