import type { Product } from './fixtures'

export const sportsProducts: Product[] = [
  {
    title: 'Running Trail Shoes',
    description: 'Grippy trail running shoes with cushioned midsole for rough terrain.',
    price: 119.99,
    inStock: true,
    category: 'sports',
  },
  {
    title: 'Yoga Mat Premium Thick',
    description: 'Non-slip yoga mat with alignment marks and carrying strap included.',
    price: 39.99,
    inStock: true,
    category: 'sports',
  },
  {
    title: 'Adjustable Dumbbell Set',
    description: 'Space-saving adjustable dumbbells from 5 to 50 pounds per hand.',
    price: 299.99,
    inStock: true,
    category: 'sports',
  },
  {
    title: 'Resistance Band Kit',
    description: 'Five bands with different resistance levels plus handles and door anchor.',
    price: 24.99,
    inStock: true,
    category: 'sports',
  },
  {
    title: 'Cycling Water Bottle',
    description: 'BPA-free squeeze bottle with quick-flow valve for hydration on rides.',
    price: 14.99,
    inStock: true,
    category: 'sports',
  },
  {
    title: 'Tennis Racket Professional',
    description: 'Lightweight graphite racket with vibration dampening for competitive play.',
    price: 159.99,
    inStock: false,
    category: 'sports',
  },
  {
    title: 'Jump Rope Speed Cable',
    description: 'Adjustable speed rope with ball bearings for double-unders and cardio.',
    price: 19.99,
    inStock: true,
    category: 'sports',
  },
  {
    title: 'Foam Roller Recovery',
    description: 'High-density foam roller for muscle recovery and flexibility training.',
    price: 29.99,
    inStock: true,
    category: 'sports',
  },
  {
    title: 'Basketball Indoor Outdoor',
    description: 'Composite leather basketball with deep channels for grip in all conditions.',
    price: 34.99,
    inStock: true,
    category: 'sports',
  },
  {
    title: 'Swim Goggles Anti-Fog',
    description: 'Leak-proof goggles with anti-fog coating and UV protection for pool use.',
    price: 17.99,
    inStock: true,
    category: 'sports',
  },
  {
    title: 'Hiking Backpack 40L',
    description: 'Ventilated back panel backpack with rain cover for multi-day hikes.',
    price: 89.99,
    inStock: true,
    category: 'sports',
  },
  {
    title: 'Boxing Gloves Training',
    description: 'Padded training gloves with wrist support for bag work and sparring.',
    price: 44.99,
    inStock: true,
    category: 'sports',
  },
  {
    title: 'Soccer Ball Official Size',
    description: 'Match quality soccer ball with thermal bonded panels for true flight.',
    price: 29.99,
    inStock: true,
    category: 'sports',
  },
  {
    title: 'Pull-Up Bar Doorway',
    description: 'No-screw doorway pull-up bar with foam grips and multiple hold positions.',
    price: 34.99,
    inStock: true,
    category: 'sports',
  },
  {
    title: 'Compression Arm Sleeves',
    description: 'UV protection arm sleeves with graduated compression for sports activities.',
    price: 14.99,
    inStock: true,
    category: 'sports',
  },
  {
    title: 'Electric Muscle Massager',
    description: 'Percussion massager with multiple heads for deep tissue muscle relief.',
    price: 79.99,
    inStock: true,
    category: 'sports',
  },
  {
    title: 'Fitness Tracker Watch',
    description: 'Waterproof fitness tracker with heart rate monitor and step counter.',
    price: 69.99,
    inStock: false,
    category: 'sports',
  },
  {
    title: 'Weightlifting Gloves',
    description: 'Padded gloves with wrist wraps for lifting protection and grip.',
    price: 22.99,
    inStock: true,
    category: 'sports',
  },
  {
    title: 'Badminton Racket Set',
    description: 'Two racket set with shuttlecocks and carrying case for recreational play.',
    price: 39.99,
    inStock: true,
    category: 'sports',
  },
  {
    title: 'Ab Roller Exercise Wheel',
    description: 'Dual wheel roller with knee pad for core strength training at home.',
    price: 19.99,
    inStock: true,
    category: 'sports',
  },
]
