import type { Product } from './fixtures'

export const clothingProducts: Product[] = [
  {
    title: 'Cotton Crew Neck T-Shirt',
    description: 'Soft breathable cotton tee available in multiple colors for daily wear.',
    price: 19.99,
    inStock: true,
    category: 'clothing',
  },
  {
    title: 'Slim Fit Denim Jeans',
    description: 'Classic denim jeans with stretch fabric for comfortable movement all day.',
    price: 49.99,
    inStock: true,
    category: 'clothing',
  },
  {
    title: 'Waterproof Winter Jacket',
    description: 'Insulated jacket with sealed seams and adjustable hood for cold weather.',
    price: 129.99,
    inStock: true,
    category: 'clothing',
  },
  {
    title: 'Merino Wool Sweater',
    description: 'Lightweight sweater made from fine merino wool for warmth without bulk.',
    price: 79.99,
    inStock: false,
    category: 'clothing',
  },
  {
    title: 'Athletic Running Shorts',
    description: 'Lightweight shorts with moisture-wicking fabric and built-in liner.',
    price: 29.99,
    inStock: true,
    category: 'clothing',
  },
  {
    title: 'Leather Belt Classic Brown',
    description: 'Full grain leather belt with brass buckle for formal and casual outfits.',
    price: 34.99,
    inStock: true,
    category: 'clothing',
  },
  {
    title: 'Fleece Zip-Up Hoodie',
    description: 'Warm fleece hoodie with front zip and kangaroo pockets for layering.',
    price: 44.99,
    inStock: true,
    category: 'clothing',
  },
  {
    title: 'Linen Button-Down Shirt',
    description: 'Breathable linen shirt perfect for warm weather and casual occasions.',
    price: 54.99,
    inStock: true,
    category: 'clothing',
  },
  {
    title: 'Compression Leggings',
    description: 'High-waist leggings with compression fit for workouts and active wear.',
    price: 39.99,
    inStock: true,
    category: 'clothing',
  },
  {
    title: 'Rain Resistant Windbreaker',
    description: 'Packable windbreaker with water-resistant coating and reflective details.',
    price: 64.99,
    inStock: true,
    category: 'clothing',
  },
  {
    title: 'Casual Canvas Sneakers',
    description: 'Lightweight canvas shoes with rubber sole for everyday casual style.',
    price: 42.99,
    inStock: true,
    category: 'clothing',
  },
  {
    title: 'Bamboo Fiber Socks Pack',
    description: 'Six-pair pack of soft bamboo fiber socks with cushioned arch support.',
    price: 18.99,
    inStock: true,
    category: 'clothing',
  },
  {
    title: 'Quilted Vest Insulated',
    description: 'Lightweight quilted vest for layering in transitional weather conditions.',
    price: 59.99,
    inStock: false,
    category: 'clothing',
  },
  {
    title: 'Stretch Chino Pants',
    description: 'Tailored chino pants with added stretch for comfort in office or weekend.',
    price: 54.99,
    inStock: true,
    category: 'clothing',
  },
  {
    title: 'Wool Blend Beanie Hat',
    description: 'Warm knit beanie in a soft wool blend for cold weather head coverage.',
    price: 16.99,
    inStock: true,
    category: 'clothing',
  },
  {
    title: 'UV Protection Sunglasses',
    description: 'Polarized lenses with UV400 protection in a lightweight durable frame.',
    price: 27.99,
    inStock: true,
    category: 'clothing',
  },
  {
    title: 'Oxford Dress Shoes',
    description: 'Classic leather oxford shoes with cushioned insole for formal events.',
    price: 89.99,
    inStock: true,
    category: 'clothing',
  },
  {
    title: 'Thermal Base Layer Top',
    description: 'Moisture-wicking thermal top for cold weather outdoor activities.',
    price: 34.99,
    inStock: true,
    category: 'clothing',
  },
  {
    title: 'Wide Brim Sun Hat',
    description: 'Packable sun hat with UPF 50 protection for beach and hiking trips.',
    price: 24.99,
    inStock: true,
    category: 'clothing',
  },
  {
    title: 'Silk Pocket Square',
    description: 'Hand-rolled silk pocket square for adding polish to suit jackets.',
    price: 22.99,
    inStock: false,
    category: 'clothing',
  },
]
