/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RelevanceRouteImport } from './routes/relevance'
import { Route as InspectorRouteImport } from './routes/inspector'
import { Route as BenchmarkRouteImport } from './routes/benchmark'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAskRouteImport } from './routes/api/ask'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RelevanceRoute = RelevanceRouteImport.update({
  id: '/relevance',
  path: '/relevance',
  getParentRoute: () => rootRouteImport,
} as any)
const InspectorRoute = InspectorRouteImport.update({
  id: '/inspector',
  path: '/inspector',
  getParentRoute: () => rootRouteImport,
} as any)
const BenchmarkRoute = BenchmarkRouteImport.update({
  id: '/benchmark',
  path: '/benchmark',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAskRoute = ApiAskRouteImport.update({
  id: '/api/ask',
  path: '/api/ask',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/benchmark': typeof BenchmarkRoute
  '/inspector': typeof InspectorRoute
  '/relevance': typeof RelevanceRoute
  '/search': typeof SearchRoute
  '/api/ask': typeof ApiAskRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/benchmark': typeof BenchmarkRoute
  '/inspector': typeof InspectorRoute
  '/relevance': typeof RelevanceRoute
  '/search': typeof SearchRoute
  '/api/ask': typeof ApiAskRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/benchmark': typeof BenchmarkRoute
  '/inspector': typeof InspectorRoute
  '/relevance': typeof RelevanceRoute
  '/search': typeof SearchRoute
  '/api/ask': typeof ApiAskRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/benchmark'
    | '/inspector'
    | '/relevance'
    | '/search'
    | '/api/ask'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/benchmark' | '/inspector' | '/relevance' | '/search' | '/api/ask'
  id:
    | '__root__'
    | '/'
    | '/benchmark'
    | '/inspector'
    | '/relevance'
    | '/search'
    | '/api/ask'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BenchmarkRoute: typeof BenchmarkRoute
  InspectorRoute: typeof InspectorRoute
  RelevanceRoute: typeof RelevanceRoute
  SearchRoute: typeof SearchRoute
  ApiAskRoute: typeof ApiAskRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relevance': {
      id: '/relevance'
      path: '/relevance'
      fullPath: '/relevance'
      preLoaderRoute: typeof RelevanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspector': {
      id: '/inspector'
      path: '/inspector'
      fullPath: '/inspector'
      preLoaderRoute: typeof InspectorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/benchmark': {
      id: '/benchmark'
      path: '/benchmark'
      fullPath: '/benchmark'
      preLoaderRoute: typeof BenchmarkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ask': {
      id: '/api/ask'
      path: '/api/ask'
      fullPath: '/api/ask'
      preLoaderRoute: typeof ApiAskRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BenchmarkRoute: BenchmarkRoute,
  InspectorRoute: InspectorRoute,
  RelevanceRoute: RelevanceRoute,
  SearchRoute: SearchRoute,
  ApiAskRoute: ApiAskRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
