export const ErrorCodes = {
  SCHEMA_INVALID_TYPE: 'SCHEMA_INVALID_TYPE',
  SCHEMA_MISSING_FIELD: 'SCHEMA_MISSING_FIELD',
  SCHEMA_DEPTH_EXCEEDED: 'SCHEMA_DEPTH_EXCEEDED',
  SCHEMA_INVALID_VECTOR_DIMENSION: 'SCHEMA_INVALID_VECTOR_DIMENSION',
  SCHEMA_INVALID_GEOPOINT: 'SCHEMA_INVALID_GEOPOINT',
  DOC_NOT_FOUND: 'DOC_NOT_FOUND',
  DOC_ALREADY_EXISTS: 'DOC_ALREADY_EXISTS',
  DOC_VALIDATION_FAILED: 'DOC_VALIDATION_FAILED',
  INDEX_NOT_FOUND: 'INDEX_NOT_FOUND',
  INDEX_ALREADY_EXISTS: 'INDEX_ALREADY_EXISTS',
  PARTITION_CORRUPTED: 'PARTITION_CORRUPTED',
  PARTITION_REBALANCING_BACKPRESSURE: 'PARTITION_REBALANCING_BACKPRESSURE',
  WORKER_CRASHED: 'WORKER_CRASHED',
  WORKER_BUSY: 'WORKER_BUSY',
  WORKER_TIMEOUT: 'WORKER_TIMEOUT',
  PERSISTENCE_SAVE_FAILED: 'PERSISTENCE_SAVE_FAILED',
  PERSISTENCE_LOAD_FAILED: 'PERSISTENCE_LOAD_FAILED',
  PERSISTENCE_DELETE_FAILED: 'PERSISTENCE_DELETE_FAILED',
  PERSISTENCE_CRC_MISMATCH: 'PERSISTENCE_CRC_MISMATCH',
  SEARCH_INVALID_FIELD: 'SEARCH_INVALID_FIELD',
  SEARCH_INVALID_VECTOR_SIZE: 'SEARCH_INVALID_VECTOR_SIZE',
  VECTOR_DIMENSION_MISMATCH: 'VECTOR_DIMENSION_MISMATCH',
  SEARCH_INVALID_FILTER: 'SEARCH_INVALID_FILTER',
  SEARCH_INVALID_MODE: 'SEARCH_INVALID_MODE',
  SEARCH_INVALID_CURSOR: 'SEARCH_INVALID_CURSOR',
  LANGUAGE_NOT_SUPPORTED: 'LANGUAGE_NOT_SUPPORTED',
  ENVELOPE_VERSION_MISMATCH: 'ENVELOPE_VERSION_MISMATCH',
  ENVELOPE_INVALID_MAGIC: 'ENVELOPE_INVALID_MAGIC',
  PARTITION_CAPACITY_EXCEEDED: 'PARTITION_CAPACITY_EXCEEDED',
  EMBEDDING_FAILED: 'EMBEDDING_FAILED',
  EMBEDDING_DIMENSION_MISMATCH: 'EMBEDDING_DIMENSION_MISMATCH',
  EMBEDDING_NO_SOURCE: 'EMBEDDING_NO_SOURCE',
  EMBEDDING_CONFIG_INVALID: 'EMBEDDING_CONFIG_INVALID',
  DOC_MISSING_REQUIRED_FIELD: 'DOC_MISSING_REQUIRED_FIELD',
  CONFIG_INVALID: 'CONFIG_INVALID',
  QUERY_ROUTING_FAILED: 'QUERY_ROUTING_FAILED',
  QUERY_PARTIAL_FAILURE: 'QUERY_PARTIAL_FAILURE',
  QUERY_NODE_TIMEOUT: 'QUERY_NODE_TIMEOUT',
  QUERY_NO_ACTIVE_REPLICA: 'QUERY_NO_ACTIVE_REPLICA',
  ALLOCATION_NO_DATA_NODES: 'ALLOCATION_NO_DATA_NODES',
  ALLOCATION_INVALID_CONFIG: 'ALLOCATION_INVALID_CONFIG',
  ALLOCATION_FAILED: 'ALLOCATION_FAILED',
} as const

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes]

export class NarsilError extends Error {
  readonly code: ErrorCode
  readonly details: Record<string, unknown>

  constructor(code: ErrorCode, message: string, details?: Record<string, unknown>) {
    super(message)
    this.name = 'NarsilError'
    this.code = code
    this.details = details ?? {}
  }
}

export function createNarsilError(code: ErrorCode, message: string, details?: Record<string, unknown>): NarsilError {
  return new NarsilError(code, message, details)
}
