export const WORKER_YOUNG_GENERATION_MB = 24
export const WORKER_HEAP_BUDGET_FRACTION = 0.5
export const MIN_WORKER_OLD_GENERATION_MB = 512

export const MIN_WORKER_COUNT = 2
export const MAX_WORKER_COUNT = 8
export const FALLBACK_CPU_COUNT = 4
export const MIN_CORES_FOR_SEVERAL_REQUEST_THREADS = 3

export const DEFAULT_BACKPRESSURE_LIMIT = 100
export const DEFAULT_REQUEST_TIMEOUT_MS = 30_000
export const SHUTDOWN_TIMEOUT_MS = 5_000
export const CONSECUTIVE_TIMEOUTS_BEFORE_DEATH = 3
