export const TOKEN_CACHE_SIZE_FLOOR = 50_000
export const TOKEN_CACHE_SIZE_CEILING = 2_000_000
export const TOKEN_CACHE_BYTES_PER_ENTRY = 200
export const NODE_TOKEN_CACHE_ENTRIES = 1_000_000
export const UNKNOWN_MEMORY_TOKEN_CACHE_ENTRIES = 200_000
export const CONSTRAINED_MEMORY_TOKEN_CACHE_FRACTION = 0.05

export const SMALL_DEVICE_MEMORY_GB = 1
export const MEDIUM_DEVICE_MEMORY_GB = 4
export const SMALL_DEVICE_TOKEN_CACHE_ENTRIES = 100_000
export const MEDIUM_DEVICE_TOKEN_CACHE_ENTRIES = 250_000
export const LARGE_DEVICE_TOKEN_CACHE_ENTRIES = 500_000

export const DEFAULT_MIN_TOKEN_LENGTH = 1
