const BYTES_PER_MB = 1024 * 1024

export const DEFAULT_MAX_BODY_BYTES = 16 * BYTES_PER_MB
export const DEFAULT_MAX_IMPORT_BYTES = 100 * BYTES_PER_MB
export const DEFAULT_MAX_LINE_BYTES = 4 * BYTES_PER_MB
export const DEFAULT_IMPORT_BATCH_SIZE = 1000
export const DEFAULT_MAX_CONCURRENT_REQUESTS = 0
export const DEFAULT_MAX_RESULT_WINDOW = 10_000
export const DEFAULT_MAX_FETCH_DOCUMENTS = 10_000
export const DEFAULT_MAX_IMPORT_ERRORS = 100
export const DEFAULT_MAX_TASK_PAGE_SIZE = 1000
export const DEFAULT_MAX_CONCURRENT_TASKS = 4

export const RESPONSE_STREAM_THRESHOLD_BYTES = 64 * 1024

export const DEFAULT_MAX_RETAINED_TASKS = 1000
export const DEFAULT_TASK_PAGE_SIZE = 20
export const TASK_PROGRESS_WRITE_INTERVAL_MS = 250
export const RUNNING_TASK_TTL_MS = 24 * 60 * 60 * 1000
export const TERMINAL_TASK_TTL_MS = 60 * 60 * 1000
